inherit_from: .rubocop_todo.yml

# 追記した規約ファイルの読込
require:
  - rubocop-rails

# This file overrides https://github.com/bbatsov/rubocop/blob/master/config/default.yml

AllCops:
 # 除外ファイル
  Exclude:
    - 'vendor/**/*'
    - 'db/**/*'
    - 'bin/**/*'
    - 'spec/**/*'
    - 'node_modules/**/*'
 # どのCOPに引っかかったのかを表示する
  DisplayCopNames: true
Rails:
  Enabled: true

# ブロックが正しく記述されているかのCOP
Layout/MultilineBlockLayout:
 # 除外
  Exclude:
    - 'spec/**/*_spec.rb'

Metrics/AbcSize:
  Max: 25

Metrics/BlockLength:
  Max: 30
  Exclude:
    - 'Gemfile'
    - 'config/**/*'
    - 'spec/**/*_spec.rb'
    - 'lib/tasks/*'

Metrics/ClassLength:
  CountComments: false
  Max: 300

Metrics/CyclomaticComplexity:
  Max: 30

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  CountComments: false
  Max: 30

Naming/AccessorMethodName:
  Exclude:
    - 'app/controllers/**/*'

# 日本語でのコメントを許可
Style/AsciiComments:
  Enabled: false

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*_spec.rb'

# モジュール名::クラス名の定義を許可
Style/ClassAndModuleChildren:
  Enabled: false

# クラスのコメント必須を無視
Style/Documentation:
  Enabled: false

# 文字リテラルのイミュータブル宣言を無視
Style/FrozenStringLiteralComment:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/WhileUntilModifier:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false
Rails/OutputSafety:
  Enabled: true
  Exclude:
    - 'app/helpers/**/*.rb'

Rails/InverseOf:
  Enabled: false

Rails/FilePath:
  Enabled: false
